[package]
name = "derive-wizard-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
derive-wizard-types = { path = "../derive-wizard-types" }
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = "2.0.111"
thiserror = "2.0"
